### ISSUE TITLE
Tutorial creación ambiente con python 3.12.0 (Windows 11)

### ISSUE THREAD

**Issue by Vichodr** [dci-courses/DatosBook#15]
Descargamos MiniForge

https://github.com/conda-forge/miniforge
![image](https://github.com/user-attachments/assets/d7f6663d-c116-470f-a093-252b43fe0808)

En la consola **Miniforge prompt**

Verificamos la version de python que estamos utilizando

`python --version`

Si no es 3.12.X hacemos lo siguiente:

`conda search python=3.12.0`

`conda install python=3.12.0`

Creamos el ambiente con python 3.12.0

`conda create -n myenv python=3.12.0`

`conda activate myenv`

Verificamos la version

`python --version`

Despues buscar la ruta de tu ambiente, que seguramente sea de este estilo:

C:\Users\TuUsuario\Mambaforge\envs\ o
C:\Users\TuUsuario\miniforge\envs\

Dentro de tu carpeta del ambiente, la abres con gitbash e instalas nbdev con:

`pip install nbdev`

**Comment by Baldr27** [comment]
Se recomienda instalar python en el sistema en vez de utilizar instaladores no oficiales.

Si abren la terminal de windows y escriben `python`, si no tuvieran python instalados Windows inmediatamente abre la Microsoft Store, en la cual se puede instalar directamente, luego de instalar python a traves de la MS pueden cerrar y abrir la terminal y python estará instalado.
Luego podran dirigirse a la carpeta donde tendran su proyecto y corren `python -m venv .venv` (puede ser python o python3 para el comando) y esto les creará una carpeta oculta para el ambiente virtual en el cual pueden trabajar libremente. Para iniciar el venv hay dos opciones (usar la que sirva primero, ambas hacen lo mismo):
`source ./.venv/bin/activate`
`.\.venv\Scripts\activate`

Luego de ejecutar esos comandos, deberia salir al final de la linea de comandos (venv), lo cual indica que está iniciado, una vez iniciado pueden ejecutar sus comandos pip para instalar nbdev y cualquier otra dependencia que se necesite.

Cada vez que se quiera desarrollar en el proyecto se debe iniciar el venv.
