### ISSUE TITLE
Error punto 4.- Logistic regresion

### ISSUE THREAD

**Issue by CarlosEsteban-afk** [dci-courses/DatosBook#24]
Se instalan las 3 dependencias existentes en el ejemplo `spacy` , `nltk` y `pandas` , estas fueron instaladas sin ni un problema.
Pero al instalar `sklearn`, me dice que la bibloteca esta deprecada y se recomienda la instalacion de otra bibloteca.
![image](https://github.com/user-attachments/assets/da337173-c731-417c-b791-e05a8febe52f)
Luego el siguiente error es encontrado y el book sugiere la que se corra 
```
#! python -m spacy download es_core_news_sm
```

Pero en ubuntu 22.04 no es posible esa solucion.

![image](https://github.com/user-attachments/assets/d6c6a190-75f8-4c71-a353-6df574788da6)

**Comment by Baldr27** [comment]
@CarlosEsteban-afk esto puede ser por multiples razones, pero sospecho que es simplemente porque para correr un comando de python en una celda de jupyter, deberias incluir el "!" antes del comando.
Por claridad, en la celda que tiene ese comando en el archivo está de la siguiente forma: "#! python command", el "#" es para comentarlo y el "!" es para ejecutar el comando en una celda de jupyter.
Por favor prueba esto para verificar si eso es lo que causa el problema.
Saludos.

**Comment by CarlosEsteban-afk** [comment]
Estimado tenias razon, el problema era mio
