### ISSUE TITLE
Como modificar el nombre de la sección techeable-machines a "Techeable Machines" sin modificar el nombre del directorio?

### ISSUE THREAD

**Issue by pavt** [dci-courses/DatosBook#5]
![Screenshot 2024-08-12 at 22 25 10](https://github.com/user-attachments/assets/05730741-994a-4d7c-9e44-6b35a5a63632)

**Comment by Baldr27** [comment]
Es posible customizar la sidebar haciendo que no sea autogenerada cada vez que se renderiza el proyecto. Esto se puede hacer cambiando "custom_sidebar" en settings.ini de False a True.
